# Use root/example as user/password credentials
version: '3.1'

services:

  app:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: db_encuestas
      DB_USER: postgres
      DB_PASSWORD: password
    ports:
      - 5002:5000
    networks:
      - web
    depends_on:
      - db
    volumes:
      - .:/opt/app
    command: poetry run python3 -m flask --app app.py --debug run --host=0.0.0.0

  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    networks:
      - web
    volumes:
      - ./database/:/docker-entrypoint-initdb.d/
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: TC01@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    networks:
      - web
    ports:
      - 5051:80

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

# Instancias de redis
  redis-master:
    image: redis:6-alpine
    volumes:
      - "./.data:/data"
    ports:
      - "6379:6379"
    environment:
      - REDIS_MASTER_HOST=127.0.0.1
 
  redis-slave:
    image: redis:6-alpine
    command: redis-server --slaveof redis-master 6379
    ports:
      - "6380:6379"
    links:
      - redis-master
    volumes:
      - "./.data:/data"
    environment:
      - REDIS_MASTER_HOST=127.0.0.1
     
  # Instance 1
  redis-sentinel:
    build: 
      context: ./redis-sentinel
    ports:
      - "26379:26379"
    links:
      - redis-master
    environment:
      - REDIS_MASTER_HOST=127.0.0.1
 
  # Instance 2
  redis-sentinel2:
    build: 
      context: ./redis-sentinel
    ports:
      - "26380:26379"
    links:
      - redis-master
    environment:
      - REDIS_MASTER_HOST=127.0.0.1
 
  # Instance 3
  redis-sentinel3:
    build: 
      context: ./redis-sentinel
    ports:
      - "26381:26379"
    links:
      - redis-master
    environment:
      - REDIS_MASTER_HOST=127.0.0.1

    
networks:
  web:
    driver: bridge

