# Use root/example as user/password credentials
version: '3.1'

services:

  app:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: db_encuestas
      DB_USER: postgres
      DB_PASSWORD: password
      MONGO_HOST: mongo 
      MONGO_PORT: 27017  
      MONGO_USER: root 
      MONGO_DB:  db_surveys
      MONGO_PASSWORD: password  
    ports:
      - 5002:5000
    networks:
      - web
    depends_on:
      - db
      - mongo  # Dependencia de MongoDB
    restart: on-failure
    volumes:
      - .:/opt/app
    command: poetry run python3 -m flask --app app.py --debug run --host=0.0.0.0

  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    networks:
      - web
    volumes:
      - ./database/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 7s
      retries: 5

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    networks:
      - web
    volumes:
      - ./mongo_data:/docker-entrypoint-initdb.d

  redis-master:
    image: redis:6-alpine
    volumes:
      - "./.data:/data"
    ports:
      - "6379:6379"
    networks:
      - web

networks:
  web:
    driver: bridge


 
  # redis-slave:
  #   image: redis:6-alpine
  #   command: redis-server --slaveof redis-master 6379
  #   ports:
  #     - "6380:6379"
  #   links:
  #     - redis-master
  #   volumes:
  #     - "./.data:/data"
  #   environment:
  #     - REDIS_MASTER_HOST=127.0.0.1
     
  # # Instance 1
  # redis-sentinel:
  #   build: 
  #     context: ./redis-sentinel
  #   ports:
  #     - "26379:26379"
  #   links:
  #     - redis-master
  #   environment:
  #     - REDIS_MASTER_HOST=127.0.0.1
 
  # # # Instance 2
  # redis-sentinel2:
  #   build: 
  #     context: ./redis-sentinel
  #   ports:
  #     - "26380:26379"
  #   links:
  #     - redis-master
  #   environment:
  #     - REDIS_MASTER_HOST=127.0.0.1
 
  # # # Instance 3
  # redis-sentinel3:
  #   build: 
  #     context: ./redis-sentinel
  #   ports:
  #     - "26381:26379"
  #   links:
  #     - redis-master
  #   environment:
  #     - REDIS_MASTER_HOST=127.0.0.1

